trailingComma: 'es5'
tabWidth: 4
semi: false
singleQuote: true
printWidth: 80
useTabs: true
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: false
proseWrap: 'preserve'
requirePragma: false
insertPragma: false
endOfLine: 'lf'
